name: Bug Report
description: File a bug report.
title: 'Bug Report: <Describe bug>'
body:
  - type: markdown
    attributes:
      value: |
        Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the `r-cards` tag.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: INCLUDE a *minimal* reproducible example (AKA a reprex). If you've never heard of a [reprex](https://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>. It'll take minutes to master creating a reprex.
      placeholder: Tell us what you see!
      value: "Brief description of the problem."
    validations:
      required: true

