---
name: ✨ Feature Request
description: Request or propose a new feature
title: 'Feature Request: <Description>'
---

Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the `r-cards` tag.
Questions about a function's use will be closed without a response.

Describe the feature and, if applicable, create a mock-up of what you'd like to see.
