name: ✨ Feature Request
description: Request or propose a new feature
title: 'Feature Request: <Description>'
body:
  - type: markdown
    attributes:
      value: |
        Do not use this form to ask a question, or ask for assistance. Instead, ask on <https://stackoverflow.com/> using the `r-cards` tag.
  - type: textarea
    id: feature
    attributes:
      label: What's the feature?
      description: Describe the feature and, if applicable, create a mock-up of what you'd like to see.
      placeholder: Tell us what you see!
      value: "Brief description of the feature request."
    validations:
      required: true
