---
output: github_document
---

```{r child='../README.Rmd'}
```

## Other Resources

```{r, echo=FALSE}
dplyr::tribble(
  ~venue, ~title, ~url_slides, ~url_video,
  "2025 PHUSE US Connect", "Analysis Results Datasets Using Open-Source Tools from the {pharmaverse}", "https://www.danieldsjoberg.com/ARD-PHUSE-workshop-2025/", NA_character_,
  "2025 PHUSE US Connect", "Harnessing Analysis Results Datasets (ARD) for Clinical Reporting in R
Our First ARD-Based Filing Experience with {cards}+{gtsummary}", "https://www.danieldsjoberg.com/ARD-PHUSE-talk-2025/", NA_character_,
  "2024 R/Pharma", "Harnessing CDISC's Emerging Analysis Results Datasets Standard", "https://www.danieldsjoberg.com/ARD-RinPharma-talk-2024/", "https://www.youtube.com/watch?v=tDb6O6a5lbc",
  "2024 R/Pharma", "Workshop: Unlocking Analysis Results Datasets ", "https://www.danieldsjoberg.com/ARD-RinPharma-workshop-2024/", NA_character_,
  "`posit::conf(2024)`", "{pharmaverse} workshop", "https://posit-conf-2024.github.io/pharmaverse/#schedule", NA_character_,
  "2024 China Pharma R User Conference", "Keynote Address", "https://www.danieldsjoberg.com/china-pharma-keynote-2024/material.html", NA_character_
) |>
  gt::gt() |>
  gt::fmt_markdown(columns = c(venue, title)) |>
  gt::fmt_url(
    columns = url_slides,
    rows = !is.na(url_slides),
    label = fontawesome::fa("display", fill = "#808080")
  ) |>
  gt::fmt_url(
    columns = url_video,
    rows = !is.na(url_video),
    label = fontawesome::fa("youtube", fill = "#808080")
  ) |>
  gt::sub_missing(missing_text = "") |>
  gt::cols_align(align = "center", columns = dplyr::contains("url")) |>
  gt::tab_options(column_labels.hidden = TRUE)
```
