---
title: "structures"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

# taken from SO https://stackoverflow.com/questions/23114654
hook_output <- knitr::knit_hooks$get("output")
knitr::knit_hooks$set(output = function(x, options) {
  lines <- options$output.lines
  if (is.null(lines)) {
    return(hook_output(x, options))  # pass to default hook
  }
  x <- unlist(strsplit(x, "\n"))
  more <- "..."
  if (length(lines)==1) {        # first n lines
    if (length(x) > lines) {
      # truncate the output, but add ....
      x <- c(head(x, lines), more)
    }
  } else {
    x <- c(more, x[lines], more)
  }
  # paste these lines together
  x <- paste(c(x, ""), collapse = "\n")
  hook_output(x, options)
})
```

```{r setup, message=FALSE}
library(cards)

ard <-
  bind_ard(
    ard_continuous(ADSL, by = "ARM", variables = "AGE"),
    ard_categorical(ADSL, by = "ARM", variables = "AGEGR1")
  ) 
```

## YAML

The `as_nested_list()` function prepares the ARD data frame to be converted to a YAML object.

```{r yaml, output.lines=15}
ard |> 
  as_nested_list() |> 
  yaml::as.yaml() |> 
  cat()
```

## JSON

The `as_nested_list()` function prepares the ARD data frame to be converted to a JSON object.

```{r json, output.lines=15}
ard |> 
  as_nested_list() |> 
  jsonlite::toJSON(pretty = TRUE)
```

Use the `jsonlite::write_json()` function to convert to JSON and write to disk simultaneously.

## REST API

TODO: Update this section

```{r}
library(plumber)
library(jsonlite)

#* @get /nested_json
#* @serializer unboxedJSON
function() {
  ard |> 
  as_nested_list() |> 
  jsonlite::toJSON(auto_unbox = TRUE)
}
```
