name: Reverse Dep Check

on:
  pull_request:
    branches: [ main ]

jobs:
  gtsummary:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install and Cache Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          # List the packages your script needs here
          extra-packages: |
            any::checked
            any::rlang
            any::cli
          # This key ensures that if you change the list above,
          # it creates a new cache rather than using an old one.
          cache-version: 1

      - name: Check Reverse Dependencies
        shell: Rscript {0}
        run: |
          Rscript -e "
          options(checked.check_envvars = c(NOT_CRAN = TRUE))
          
          tryCatch({
            checked::check_rev_deps(
              path = '.', 
              n = parallel::detectCores() - 2L, 
              repos = c('https://ddsjoberg.r-universe.dev', 'https://cloud.r-project.org')
            )
          }, error = function(e) {
            cli::cli_abort(
              c('This PR newly breaks reverse dependencies (like {.pkg gtsummary})',
                '!' = 'The PR must be updated as to not break reverse dependencies.',
                'i' = 'In rare cases where the break is acceptable, the change {.emph MUST} first be approved by Daniel Sjoberg (danieldsjoberg@gmail.com) {.emph before} this PR could potentially be merged.',
                'x' = e\$message
              )
            )
          })
          "
